"""Validate PMS document structure and regenerate the derived ID navigation index.

Run from any directory: python docs/product-master-specification/validate_pms.py
This validates document integrity, never implementation or functional completeness.
"""

from collections import defaultdict
from decimal import Decimal
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parent
ID_PATTERN = re.compile(r"\bPMS-(?:PRD-(?:MAR|PCC|BIZ|DEV|OCC|MKT)|[A-Z]+(?:-[A-Z]+)*-\d{3,6}(?:-\d{3})?)\b")


def read(name):
    return (ROOT / name).read_text(encoding="utf-8")


def require(condition, message):
    if not condition:
        raise SystemExit("FAIL: " + message)


volume0 = read("VOLUME-00-MASTER-INDEX-AND-GOVERNANCE.md")
apps_text = read("APPLICATION-REGISTRY.md")
toc = read("MASTER-TABLE-OF-CONTENTS.md")
registries = read("MASTER-REGISTRIES.md")
require(re.findall(r"^## 0\.(\d+) ", volume0, re.M) == list(map(str, range(1, 19))), "Volume 0 requires all 18 starting sections")
require(list(map(int, re.findall(r"^### S(\d+) ", toc, re.M))) == list(range(1, 71)), "All 70 source subjects must remain indexed")
products = re.findall(r"^\| (PMS-PRD-\w+) \|", volume0, re.M)
require(len(products) == len(set(products)) == 6, "Exactly six unique products required")
applications = re.findall(r"^\| (PMS-APP-[A-Z]+-\d+) \| (PMS-PRD-[A-Z]+) \| ([^|]+)", apps_text, re.M)
modules = re.findall(r"^\| (PMS-MOD-[A-Z]+-\d+-\d+) \| (PMS-APP-[A-Z]+-\d+) \|", apps_text, re.M)
require(len(applications) == len({a[0] for a in applications}) and len(applications) >= 44, "Application IDs duplicate or initial records missing")
require(len(modules) == len({m[0] for m in modules}) and len(modules) >= 422, "Module IDs duplicate or initial records missing")
require(all(a[1] in products for a in applications), "Unknown application parent product")
require(all(m[1] in {a[0] for a in applications} for m in modules), "Unknown module parent application")
for builder in ("Application and Full-Stack Builder", "Website Builder"):
    require(any(builder in a[2] and a[1] == "PMS-PRD-DEV" for a in applications), "Builder product ownership mismatch: " + builder)
require(len(re.findall(r"^## 0\.6\.(?:[1-9]|1\d|20) .* Registry$", registries, re.M)) == 20, "All 20 registries required")

# Enumerated references remain navigation records, not claims of full specifications.
occurrences = defaultdict(list)
files = sorted(p for p in ROOT.glob("*.md") if p.name not in {"REGISTRY-INDEX.md", "SOURCE-BRIEF.md", "VERIFICATION.md"})
require(len(files) >= 7, "No/insufficient authored document targets")
for path in files:
    for line_number, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        for identifier in dict.fromkeys(ID_PATTERN.findall(line)):
            occurrences[identifier].append((path.name, line_number))

index = ["# Allocated PMS ID Navigation Index", "", "Generated by `python docs/product-master-specification/validate_pms.py`. Source scope: authored Markdown volumes and registries; excludes this derived index, source brief and verification report. This indexes concrete ID mentions, including reserved artifacts and test scenarios. A reference is not proof of complete specification or implementation. Owning records retain decision/evidence status.", "", "| ID | First document reference | Other referenced documents |", "| --- | --- | --- |"]
for identifier, locations in sorted(occurrences.items()):
    first = locations[0][0]
    others = sorted({filename for filename, _ in locations if filename != first})
    index.append(f"| {identifier} | [{first}]({first}) | " + "; ".join(f"[{name}]({name})" for name in others) + " |")
(ROOT / "REGISTRY-INDEX.md").write_text("\n".join(index) + "\n", encoding="utf-8")

link_count = 0
for path in ROOT.glob("*.md"):
    content = path.read_text(encoding="utf-8")
    for target in re.findall(r"\[[^\]]*\]\(([^)]+)\)", content):
        if "://" in target or target.startswith("#"):
            continue
        require((path.parent / target.split("#")[0]).exists(), f"Broken link in {path.name}: {target}")
        link_count += 1
    require(content.count("```mermaid") == len(re.findall(r"```mermaid\n[\s\S]*?\n```", content)), "Unclosed Mermaid block in " + path.name)

# Independent decimal arithmetic for the synthetic worked examples in Volume 1.
api = Decimal(400000) * Decimal("0.00002")
storage = Decimal(10) * Decimal("0.10")
usage = api + storage + Decimal(12)
invoice = Decimal(100) + usage - min(Decimal(5), usage)
require(invoice == Decimal(116), "Worked invoice arithmetic")
cost = sum(map(Decimal, ["15", "6", "10", "3.48"]))
profit = invoice - cost
require(profit == Decimal("81.52"), "Worked gross profit")
require((profit / invoice * 100).quantize(Decimal("0.01")) == Decimal("70.28"), "Worked gross margin")
require((Decimal(600) / profit).quantize(Decimal("0.01")) == Decimal("7.36"), "CAC payback")
require(profit / Decimal("0.02") == Decimal(4076), "Simplified LTV")
require(min(Decimal(2000) * Decimal("0.15") * Decimal("0.8"), Decimal(200)) * Decimal(6000) == Decimal(1200000), "Capacity-limited SOM illustration")
require("synthetic" in read("VOLUME-01-BUSINESS-AND-COMMERCIAL-FOUNDATION.md").lower(), "Synthetic assumptions must remain labeled")

# Marketing field coverage is a document check, not a semantic completeness claim.
marketing_file = ROOT / "VOLUME-03-MARKETING-FEATURES.md"
if marketing_file.exists():
    marketing = marketing_file.read_text(encoding="utf-8")
    blocks = re.split(r"^### 3A\.2\.\d+ .+$", marketing, flags=re.M)[1:]
    require(len(blocks) == 21, "All 21 Marketing modules require significant feature records")
    module_ids = re.findall(r"^\| Module \| (PMS-MOD-MAR-\d+-\d+) \|$", marketing, re.M)
    expected_modules = {m[0] for m in modules if m[0].startswith("PMS-MOD-MAR-")}
    require(len(module_ids) == len(set(module_ids)) == 21 and set(module_ids) == expected_modules, "Marketing module coverage/uniqueness")
    required_fields = ["Feature ID", "Name", "Product", "Application", "Module", "Purpose", "Business value", "Actors", "Personas", "Preconditions", "Trigger", "Main workflow", "Alternate workflows", "Exception workflows", "Postconditions", "UI behavior / components", "Inputs", "Outputs", "Validation", "Business rules", "Data entities", "State transitions", "Permissions", "APIs", "Events", "Integrations", "Notifications", "Audit requirements", "Security requirements", "Privacy requirements", "Performance requirements", "Accessibility requirements", "Localization", "Configuration", "Error handling", "Edge cases", "Dependencies", "Requirement / acceptance criteria", "Test scenarios"]
    for number, block in enumerate(blocks, 1):
        labels = re.findall(r"^\| ([^|]+) \|", block, re.M)
        for field in required_fields:
            require(field in labels, f"Marketing feature {number} missing {field}")
    marketing_core = read("VOLUME-03-MARKETING-SITE.md")
    for kind in ["SCR", "PER", "ENT", "API", "EVT", "INT", "NTF", "RPT"]:
        referenced = set(re.findall(rf"PMS-{kind}-MAR-\d{{6}}", marketing))
        defined = set(re.findall(rf"^\| (PMS-{kind}-MAR-\d{{6}}) \|", marketing_core, re.M))
        require(referenced <= defined, f"Unresolved Marketing {kind} references: {referenced - defined}")
    print("PASS Marketing document coverage: 21 unique module features, required field labels and resolved screen/permission/entity/API/event/integration/notification/report references.")

print(f"PASS document integrity: 18 starting sections; 70 source subjects; 6 products; {len(applications)} applications; {len(modules)} modules; 20 registries; {len(occurrences)} indexed concrete IDs; {link_count} resolving local links.")
print("PASS decimal arithmetic: invoice, margin, CAC payback, simplified LTV and capacity-limited market illustration.")
print("NOT ASSESSED: complete functional depth, owner approval, remote URL availability, Mermaid rendering or product implementation.")
