name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci:
    uses: kannan19302/unierp-workspace/.github/workflows/reusable-ci.yml@730dacc512d50e5b10ed2b5f6e80bf4d41c9010b
